import Head from "next/head";

import SectionTitle from "@/components/ui/SectionTitle";
import FaqAccordion from "@/components/faqPage/FaqAccordion";
import AdvantagesAccordion from "@/components/faqPage/AdvantagesAccordion";

const FaqPage = () => {
  return (
    <>
      <Head>
        <title>Next App with Chakra UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionTitle title="Preguntas frecuentes" />
      <FaqAccordion />
      <AdvantagesAccordion />
    </>
  );
};

export default FaqPage;
